#!/bin/bash

set -e

read -p "Username: " USERNAME
read -s -p "Password: " PASSWORD

TOKEN=$(curl 'https://opendata.nationalrail.co.uk/authenticate' \
     --data-urlencode "username=$USERNAME" \
     --data-urlencode "password=$PASSWORD" | jq -r .token)

curl 'https://opendata.nationalrail.co.uk/api/staticfeeds/2.0/fares' -H "X-Auth-Token: $TOKEN" --output fares.zip
curl 'https://opendata.nationalrail.co.uk/api/staticfeeds/3.0/timetable' -H "X-Auth-Token: $TOKEN" --output timetable.zip
