#!/bin/bash

set -e

FARE_DIR=fare-data-$(unzip -l fares.zip | grep TOC | perl -pe's/.*FAF(\d+).*/$1/')
TIMETABLE_DIR=timetable-data-$(unzip -l timetable.zip | grep MCA | perl -pe's/.*TTF(\d+).*/$1/')

PROCESS=""
if [ ! -e $FARE_DIR ]; then
    PROCESS=1
    unzip -d $FARE_DIR fares.zip
fi
rm fares.zip
if [ ! -e $TIMETABLE_DIR ]; then
    PROCESS=1
    unzip -d $TIMETABLE_DIR timetable.zip
fi
rm timetable.zip

if [ -n "$PROCESS" ]; then
    set -x
    source venv/bin/activate
    python parse-tocs $FARE_DIR
    python parse-stations $FARE_DIR
    python parse-restrictions $FARE_DIR
    python parse-fares $FARE_DIR
    python parse-ndf $FARE_DIR
    python parse-trains $FARE_DIR $TIMETABLE_DIR
    python merge-fares-ndf $FARE_DIR
    git add data/fares
fi
